#ifndef BUTACTIONS_H
#define BUTACTIONS_H

enum ActionType { CREATE_CIRCLE, CHANGE_VISIBILITY, INCREASE_SIZE, DECREASE_SIZE, RANDOM_POS, ACTION, CLEAR_VECTOR, FILL_VECTOR, MOVE_CIRCLES_RIGHT, MOVE_CIRCLES_LEFT, MOVE_CIRCLES_UP, MOVE_CIRCLES_DOWN};

#endif